version: '3'

services:
  drupal:
    image: drupal:10-apache
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    restart: always
    depends_on:
      - drupal-postgres-db

  drupal-postgres-db:
    image: postgres:17.0-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: extSupusr
      POSTGRES_PASSWORD: ext#2024@drupaldb
      POSTGRES_DB: extDrupaldb
    volumes:
      - ./postgres-data/drupal-db:/var/lib/postgresql/data
    restart: always

volumes: 
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
