version: '3.1'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:latest
    restart: always
    ports:
    - "2181:2181"
    environment:
      env: dev-test
    
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    env_file:
      - ".env"