version: '3'
services:
  db:
    image: mysql:9.0.1-oraclelinux9
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 30s
    environment:
      MYSQL_ROOT_PASSWORD: 2Brss@12345
      MYSQL_DATABASE: test-db
      MYSQL_USER: composed_user
      MYSQL_PASSWORD: 2Brss@54321
    # ports:
    #   - 3307:3306
    #   - 3308:33060
    volumes:
      - ./mysql/data:/var/lib/mysql

  nginx:
    image: nginx:mainline-bookworm
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 30s
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
